name: Sync to GitLab

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"

    - name: Add GitLab remote
      run: |
        git remote remove gitlab || true
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/wmystc/wmystc.gitlab.io.git

    - name: Fetch all branches from GitLab
      run: git fetch --all

    - name: Pull and push all branches
      run: |
        for remote_branch in $(git ls-remote --heads gitlab | awk '{print $2}'); do
          branch=${remote_branch#refs/heads/}
          git checkout $branch || git checkout -b $branch
          git pull gitlab $branch --rebase
          git push gitlab $branch
        done

    - name: Push all tags to GitLab
      run: git push gitlab --tags
